# Generated by Django 5.2.3 on 2025-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.IntegerField(unique=True)),
                ('holder_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('qualification_name', models.CharField(max_length=100)),
                ('major_specialization', models.CharField(max_length=100)),
                ('awarding_year', models.IntegerField()),
                ('country_of_education', models.CharField(max_length=100)),
                ('awarding_institution', models.CharField(max_length=200)),
                ('institution_status', models.CharField(max_length=100)),
                ('qualification_type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('evaluation_notes', models.TextField()),
            ],
        ),
    ]
